services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: home_service
    ports:
      - "5432:54320"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  